AWSTemplateFormatVersion: "2010-09-09"

Description: "This is template to create S3 bucket with a certain prefix and a name"

Parameters:

  S3BucketPrefix:
    Type: String


Resources:


  WorkshopS3Bucket:
    Type: AWS::S3::Bucket

