AWSTemplateFormatVersion: '2010-09-09'
Description: This is template to create S3 bucket with a certain prefix and a name
Parameters:
  S3BucketPrefix:
    Type: String
Resources:
  RandomBucketNameGeneratorLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: revanth-source
        S3Key: 1d224d929446dee0b694fdb25ac990ff
      FunctionName: lambda-to-generate-bucket-name
      Description: Lambda to generate a random bucket name
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - RandomBucketNameGeneratorLambdaRole
        - Arn
      Runtime: python3.7
      Timeout: 180
  RandomBucketNameGeneratorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: RandomBucketNameGeneratorLambdaLogPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
  GenerateBucketName:
    Type: Custom::NameGenerato
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - RandomBucketNameGeneratorLambda
        - Arn
      bucket_prefix:
        Ref: S3BucketPrefix
  WorkshopS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::GetAtt:
        - GenerateBucketName
        - bucket_name
